Titov/feature add screen logic
CrazyApple888/BicycleAccounter pull request #9
Opened 2022-04-03 14:38 UTC by Romchirik

Я великий бабизян дай кокос

2022-04-03 16:08 UTC, CrazyApple888 requested changes

2022-04-03 16:08 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/presentation/viewmodel/AddBicycleViewModel.kt
> +    fun addBicycle(bicycle: Bicycle) {
А если закрыли экран до того как велосипед сохранился?

2022-04-03 16:08 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/presentation/viewmodel/DetailedBicycleViewModel.kt
> +                        "Unable to load bicycle with id $id: ${result.message ?: "No error message"}"
Пользователь тоже хочет узнать об ошибке вместо бесконечного ожидания

2022-04-03 16:08 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/ui/fragment/AddBicycleFragment.kt
> +                Bicycle(
Не уверен, что фрагмент должен заниматься созданием моделек

2022-04-03 16:08 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/ui/fragment/AddBicycleFragment.kt
> +    private fun matchesBicycleName(name: String) = name.all { true }
Выглядит бесполезно ))

2022-04-04 04:20 UTC, Romchirik commented on app/src/main/java/ru/nsu/fit/domain/model/LoggingTags.kt
> +object LoggingTags {
Имхо, так выразительнее + можно поменять в любой момент (хз правда зачем)

2022-04-04 04:24 UTC, Romchirik commented on app/src/main/java/ru/nsu/fit/ui/fragment/AddBicycleFragment.kt
> +    private fun matchesBicycleName(name: String) = name.all { true }
Ну конкретно в этом случае да, но ща можно быстро поменять правила по которым поля валидирутся

2022-04-04 04:34 UTC, Romchirik commented on app/src/main/java/ru/nsu/fit/ui/fragment/AddBicycleFragment.kt
> +                Bicycle(
Ну а вариантов тут не сильно много, городить метод с тонной параметров тоже фигня

2022-04-06 12:27 UTC, CrazyApple888 requested changes

2022-04-06 12:27 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/data/model/TransactionFailure.kt
> +enum class TransactionFailure(private val id: Int = 0) {
id кажется нигде не используется, мб убрать?

2022-04-06 12:27 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/domain/model/LoggingTags.kt
> +    const val USECASE = "BicycleUseCase"
А если не Bicycle? Очередной повод вынести это в отдельный интерфейс с тегом

2022-04-06 12:27 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/data/repository/BicycleRepositoryImpl.kt
>  class BicycleRepositoryImpl @Inject constructor(
Если смотреть заветы гугла, то это скорее manager уже, а не репозиторий

2022-04-06 12:27 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/data/repository/BicycleRepositoryImpl.kt
>                  if (null == it) {
Давай все же it != null. Везде

2022-04-06 12:27 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/data/repository/BicycleRepositoryImpl.kt
> +            if (0 == sizeId.await() || 0 == colorId.await() ||
sizeId.await() == 0 и тд

2022-04-06 12:27 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/data/repository/BicycleRepositoryImpl.kt
> +                        bicycle,
Давай тоже через именованый параметр

2022-04-06 12:27 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/domain/usecase/AddBicycleUseCase.kt
> +    suspend fun getWheelSizes(): Flow<Result<List<WheelSize>>> =
Это все же надо разделить. По сути все это используется для дропдаунов, предлагаю завести под это отдельную сущность и для нее свой usecase

2022-04-06 12:27 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/ui/fragment/AddBicycleFragment.kt
> +                Bicycle(
Вьюха не должна заниматься созданием моделей

2022-04-06 12:27 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/ui/fragment/AddBicycleFragment.kt
> +    private fun matchesBicycleName(name: String) = name.all { true }
Давай уберем

2022-04-06 14:11 UTC, Romchirik commented on app/src/main/java/ru/nsu/fit/domain/model/LoggingTags.kt
> +    const val USECASE = "BicycleUseCase"
А? Это просто пул констант

2022-04-06 14:12 UTC, Romchirik commented on app/src/main/java/ru/nsu/fit/data/repository/BicycleRepositoryImpl.kt
>                  if (null == it) {
Нет, так безопаснее, на jvm точно

2022-04-06 14:12 UTC, Romchirik commented on app/src/main/java/ru/nsu/fit/data/repository/BicycleRepositoryImpl.kt
> +            if (0 == sizeId.await() || 0 == colorId.await() ||
То же самое что и в комменте выше

2022-04-07 03:25 UTC, Romchirik commented on app/src/main/java/ru/nsu/fit/data/model/TransactionFailure.kt
> +enum class TransactionFailure(private val id: Int = 0) {
Используется в методах добавления цвета например, или чекни BicycleManagerImpl,  там в в самом конце дергается ординал

2022-04-07 17:30 UTC, CrazyApple888 requested changes

2022-04-07 17:30 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/ui/fragment/AddBicycleFragment.kt
> +        binding.purchasePriceInput.doOnTextChanged { text, _, _, _ ->
Такие вещи делаются сквозь viewModel: в колбеке тыкаешь метод вью модели, она делает все нужные операции и тыкает ивент, если нужно. Получается, что фрагмент занимается только отображением, а viewModel логикой какой-то. Кроме того, данный подход потом проще рефакторить, переиспользовать.
Ну крч надо переделывать )Относится ко всем листенерам

2022-04-07 17:30 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/ui/fragment/AddBicycleFragment.kt
> +    override fun onDestroyView() {
Микродокапывание чисто от себя: такие методы лучше в конце писать, потому что существенной нагрузки не несут. а только отвлекают от последовательного чтения)

2022-04-07 17:30 UTC, CrazyApple888 commented on app/src/main/java/ru/nsu/fit/ui/fragment/AddBicycleFragment.kt
> +    private fun onSubmit() {
Опять же сквозь viewModel

2022-04-07 18:44 UTC, merged